# overlays/dev/external-secret-patch.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: appsettings-externalsecret
spec:
  data:
  - secretKey: appsettings.json
    remoteRef:
      key: dev/appsettings
      property: appsettings.json