# base/external-secret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: appsettings-externalsecret
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: appsettings-secret
  data:
  - secretKey: appsettings.json
    remoteRef:
      key: appsettings
      property: appsettings.json